# This is a basic workflow to help you get started with Actions
name: ch02_01_challenge.yml
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ ch02_01_challenge ]

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: Step two
      run: |
        echo fecha en ubuntu first job
        date

  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: Step two
      run: |
        Write-Output "fecha en windows second job"
        date

  job3:
    name: Third job
    runs-on: macos-latest
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: Step two
      run: |
        echo La fecha en macos  third job
        date
  job4:
    name: Third job
    needs: [job1,job2,job3]
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: Step two
      run: |
        date
        echo fecha Ultimo job