# This is a basic workflow to help you get started with Actions
name: first
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ ch02_01 ]

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: Step two
      run: env | sort

  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: Step two
      run: "Get-ChildItem Env: |sort-object name"

  job3:
    name: Third job
    needs: [job1,job2]
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: Step two
      run: echo "HELLO I'M JOB3"
